---
language: python
python: "2.7"

# Install ansible
before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks:
    urls:
    #- https://galaxy-qa.ansible.com/api/v1/notifications/
    - https://45.79.158.144/api/v1/notifications/
    on_success: always
    on_failure: always
